### ISSUE TITLE
Customize extension

### ISSUE THREAD

**Issue by sebastientromp** [tribal2/zip-build#1]
Hey, thanks for making this!

Would it be possible to have another parameter we can pass it to change the extension of the zipped file?

Also, having a way to customize the output name would be nice, but I can totally live with the current format.

Cheers :)
Seb

**Comment by tribal2** [comment]
Thanks for the suggestion @sebastientromp. Please don't forget to star ⭐ this repo if it's helping you 😃

**Comment by sebastientromp** [comment]
Thanks!

Actually my need is a little bit different from what has been implemented: I want to do a zip, but change the extension only (the app I'm bundling it for uses a custom extension for their bundles, but it's a zip behind the scenes).
Adding the full name in parameter doesn't really work for me, as I don't have an easy access to the package name and version from inside the package.json file (I could write my own custom script though, but had hoped to not have to :) ).

So what I would need is either:
- the ability to just rename the extension (which would be independent from the format)
- the ability to provide a name template with placeholders, like "PACKAGENAME_PACKAGEVERSION.myext", where PACKAGEVERSION would be automatically replaced with the version from the package.json.

Do you think it would make sense to implement this? 
Otherwise I'll look into building my own script to extract the variable names from the package.json

**Comment by tribal2** [comment]
Adding the option `n` or `name`: `zip-build -n`, the script is going to ask for a filename+ext everytime... I don't know if this works for you. Soon I'll implement an option to let you provide a template with placeholders for the output filename. PRs are also very welcomed 😊

**Comment by sebastientromp** [comment]
My use case is that I want to zip my dist folder after it has been built, and I'm calling zip-build from the "scripts" section in package.json.

From there, I can't unfortunately access the current version of the app, so to make it work as it is I would need to write a custom script in order to retrieve the app version. Doable, but something I would like to avoid, especially since zip-build already handles it 👍 

And thanks again for making this tool, it's the only one that I found that was working how I wanted it to :)

**Comment by sebastientromp** [comment]
Perfect, that is exactly what I need. Thanks a lot!
