### ISSUE TITLE
Feature request - name the output

### ISSUE THREAD

**Issue by alexander-williamson** [tribal2/zip-build#11]
Is there a way to name the output?

Right now you generate a file underneath the output dir, and I want to specify the name.

```
zip-build my-folder-to-compress my-app.1.0.0.zip
```

**Comment by tribal2** [comment]
Hi! you can use `--template (-t)` option to override the default template for output filename: `%NAME%_%VERSION%_%TIMESTAMP%.%EXT%`

In this template string you can use any value from your `package.json` file or you can use a hardcoded name, for example:

` zip-build input -t anything+%VERSION%.%EXT%` will generate `anything+0.0.1.zip`
