### ISSUE TITLE
Add option to force overwrite output zip file.

### ISSUE THREAD

**Issue by BigPackie** [tribal2/zip-build#3]
**Usage:**
Using as script with positionals from package.json:  "backup": "zip-build".

**Behavior:**
If the zip file already exists, a prompt is presented 

```
  > Rename output file appending the current timestamp
  Rename output file with another name
  Overwrite existing file
  Exit
```

This requires manual intervention from the user.

**Resolution:**
Add an option/flag to automatically overwrite files (and optionally a flag for all the other choices)

**Comment by BigPackie** [comment]
Not fixed. Cannot even save files annymore, cause the timestamp contains ":" which is not a valid character for file names (I am on Windows using PowerShell as console.).  

I mean adding the timestamp (in seconds format) is a bypass solution to the problem. Would it be possible to add an optional flag so we can choose what is the default behavior?

**Comment by tribal2** [comment]
Ohh Windows 🤦‍♂️... I will fix it tonight
